env:
    global:
        - PACKAGE="SetWindowTitle" # Package name
        - SUBLIME_TEXT_VERSION="3"
        # use UNITTESTING_TAG to specific tag of UnitTesting
        # - UNITTESTING_TAG="master"

# multiple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          # ST uses python 3.3 but it's not supported by Travis anymore...
          # python: 3.3

services:
    # Starts a graphical environment
    - xvfb

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # install Package Control and package dependencies
    # - sh travis.sh install_package_control

script:
    - sh travis.sh run_tests --coverage

after_success:
    - coveralls

notifications:
    email: false
